language: node_js
node_js:
  - 'node'
  - '12'
  - '10'
  - '8'
cache: yarn

script:
  - yarn test
  - yarn integrate

jobs:
  include:
    - stage: deploy
      name: "NPM Release"
      node_js: '10'
      script: yarn build

      # Using semantic-release, deploy a new version of the library
      deploy:
        skip_cleanup: true
        provider: script
        script: npx semantic-release
