language: node_js
node_js:
  - 'node'
  - '10'
  - '8'

script: yarn test

jobs:
  include:
    - stage: NPM Release
      node_js: '10'
      script: yarn build

      # Using semantic-release, deploy a new version of the library
      deploy:
        skip_cleanup: true
        provider: script
        script: npx semantic-release
